/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/companies/{company_id}/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Connection */
        get: operations["check_connection_companies__company_id__connection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/business-sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Business Sectors */
        get: operations["list_business_sectors_companies__company_id__business_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_companies__company_id__categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skills */
        get: operations["list_skills_companies__company_id__skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Countries */
        get: operations["list_countries_companies__company_id__countries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Latest Jobs */
        get: operations["list_latest_jobs_companies__company_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/{company_id}/candidates/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Candidates */
        post: operations["search_candidates_search__company_id__candidates_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddressSchema */
        AddressSchema: {
            /** Address1 */
            address1: string | null;
            /** Address2 */
            address2: string | null;
            /** City */
            city: string | null;
            /** State */
            state: string | null;
            /** Zip */
            zip: string | null;
            /** Country Id */
            country_id: number | null;
        };
        /** AnonymisedCandidate */
        AnonymisedCandidate: {
            /** External Id */
            external_id: string;
            /** Company Id */
            company_id: string;
            /** Title */
            title: string | null;
            /** Category */
            category: string | null;
            /** Business Sector */
            business_sector: string | null;
            /** Owner Name */
            owner_name: string | null;
            resume: components["schemas"]["CandidateResume"] | null;
            match?: components["schemas"]["CandidateMatch"] | null;
        };
        /** BusinessSectorsSchema */
        BusinessSectorsSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Date Added */
            date_added: string | null;
        };
        /**
         * CandidateMatch
         * @description `MatchScore` minus `candidate_id` — already keyed onto its `AnonymisedCandidate`.
         */
        CandidateMatch: {
            /** Score */
            score: number;
            /** Skills Score */
            skills_score: number;
            /** Experience Score */
            experience_score: number;
            /** Fit Score */
            fit_score: number;
            /** Reasons */
            reasons: string[];
        };
        /**
         * CandidateResume
         * @description The identity reveal. The candidate's CV is fetched and parsed live via Bullhorn's
         *     résumé parser as part of the search response, never persisted (rule 1) and never
         *     logged (rule 4). Deliberately its own nested type: this is the one point where PII is
         *     allowed to leave, as a business decision, not the default shape of a candidate
         *     response. `parsed` is Bullhorn's own structured-candidate output — shape is whatever
         *     their parser returns, not remodelled here, since exact fields vary by resume.
         */
        CandidateResume: {
            /** File Name */
            file_name: string;
            /** Parsed */
            parsed: {
                [key: string]: unknown;
            };
        };
        /** CandidateSearchRequest */
        CandidateSearchRequest: {
            /** Category Ids */
            category_ids?: number[];
            /** Skill Ids */
            skill_ids?: number[];
            /** Business Sector Ids */
            business_sector_ids?: number[];
            /** Country Ids */
            country_ids?: number[];
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Limit
             * @default 10
             * @enum {integer}
             */
            limit: 10 | 20 | 30 | 40 | 50;
        };
        /** CandidateSearchResponse */
        CandidateSearchResponse: {
            /** Company Id */
            company_id: string;
            /** Candidates */
            candidates: components["schemas"]["AnonymisedCandidate"][];
            /** Total Count */
            total_count: number;
            /** Capped */
            capped: boolean;
        };
        /** CategorySchema */
        CategorySchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Enabled */
            enabled: boolean;
            /** Skills */
            skills: number[];
            /** Specialties */
            specialties: number[];
            /** Type */
            type: string | null;
            /** Date Added */
            date_added: string | null;
            /** Occupation */
            occupation: string | null;
        };
        /** ConnectionRead */
        ConnectionRead: {
            /** Company Id */
            company_id: string;
            /** Name */
            name: string;
            /** Configured */
            configured: boolean;
            /** Connected */
            connected: boolean;
            /** Rest Url Present */
            rest_url_present: boolean;
            /** Detail */
            detail?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobOrderSchema */
        JobOrderSchema: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Status */
            status: string | null;
            /** Employment Type */
            employment_type: string | null;
            /** Is Open */
            is_open: boolean | null;
            /** Is Public */
            is_public: number | null;
            /** Date Added */
            date_added: string | null;
            /** Date End */
            date_end: string | null;
            /** Date Last Published */
            date_last_published: string | null;
            /** Start Date */
            start_date: string | null;
            address: components["schemas"]["AddressSchema"] | null;
            /** Benefits */
            benefits: string | null;
            /** Bonus Package */
            bonus_package: string | null;
            /** Pay Rate */
            pay_rate: number | null;
            /** Salary */
            salary: number | null;
            /** Salary Unit */
            salary_unit: string | null;
            /** Public Description */
            public_description: string | null;
            /** Published Zip */
            published_zip: string | null;
            /** Travel Requirements */
            travel_requirements: string | null;
            /** Will Relocate */
            will_relocate: boolean | null;
            /** Will Sponsor */
            will_sponsor: boolean | null;
            /** Years Required */
            years_required: number | null;
            /** Category */
            category: string | null;
            /** Business Sector */
            business_sector: string | null;
            /** Owner Name */
            owner_name: string | null;
            /** Published Category */
            published_category: string | null;
            /** Response User Name */
            response_user_name: string | null;
        };
        /** TaxonomyOption */
        TaxonomyOption: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    check_connection_companies__company_id__connection_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_business_sectors_companies__company_id__business_sectors_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessSectorsSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_companies__company_id__categories_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorySchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_companies__company_id__skills_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyOption"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_countries_companies__company_id__countries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyOption"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_latest_jobs_companies__company_id__jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOrderSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_candidates_search__company_id__candidates_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
