/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Connection */
        get: operations["check_connection_companies__company_id__connection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/business-sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Business Sectors */
        get: operations["list_business_sectors_companies__company_id__business_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_companies__company_id__categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skills */
        get: operations["list_skills_companies__company_id__skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Countries */
        get: operations["list_countries_companies__company_id__countries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Latest Jobs */
        get: operations["list_latest_jobs_companies__company_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/{company_id}/candidates/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Candidates */
        post: operations["search_candidates_search__company_id__candidates_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-orders/{company_id}/check-new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check New Job Orders */
        post: operations["check_new_job_orders_job_orders__company_id__check_new_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-orders/{company_id}/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get New Job Orders */
        get: operations["get_new_job_orders_job_orders__company_id__new_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-orders/{company_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Job Orders */
        post: operations["sync_job_orders_job_orders__company_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-orders/{company_id}/stored": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stored Job Orders */
        get: operations["list_stored_job_orders_job_orders__company_id__stored_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddressSchema */
        AddressSchema: {
            /** Address1 */
            address1: string | null;
            /** Address2 */
            address2: string | null;
            /** City */
            city: string | null;
            /** State */
            state: string | null;
            /** Zip */
            zip: string | null;
            /** Country Id */
            country_id: number | null;
            /** Country Name */
            country_name: string | null;
        };
        /** AnonymisedCandidate */
        AnonymisedCandidate: {
            /** External Id */
            external_id: string;
            /** Company Id */
            company_id: string;
            /** Title */
            title: string | null;
            /** Category */
            category: string | null;
            /** Business Sector */
            business_sector: string | null;
            /** Owner Name */
            owner_name: string | null;
            resume: components["schemas"]["CandidateResume"] | null;
            match?: components["schemas"]["CandidateMatch"] | null;
        };
        /** BusinessSectorsSchema */
        BusinessSectorsSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Date Added */
            date_added: string | null;
        };
        /** CandidateMatch */
        CandidateMatch: {
            /** Score */
            score: number;
            /** Skills Score */
            skills_score: number;
            /** Experience Score */
            experience_score: number;
            /** Fit Score */
            fit_score: number;
            /** Reasons */
            reasons: string[];
        };
        /** CandidateResume */
        CandidateResume: {
            /** File Name */
            file_name: string;
            /** Parsed */
            parsed: {
                [key: string]: unknown;
            };
        };
        /** CandidateSearchRequest */
        CandidateSearchRequest: {
            /** Category Ids */
            category_ids?: number[];
            /** Category Names */
            category_names?: string[];
            /** Skill Ids */
            skill_ids?: number[];
            /** Skill Names */
            skill_names?: string[];
            /** Business Sector Ids */
            business_sector_ids?: number[];
            /** Business Sector Names */
            business_sector_names?: string[];
            /** Country Ids */
            country_ids?: number[];
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Limit
             * @default 10
             * @enum {integer}
             */
            limit: 10 | 20 | 30 | 40 | 50;
        };
        /** CandidateSearchResponse */
        CandidateSearchResponse: {
            /** Company Id */
            company_id: string;
            /** Candidates */
            candidates: components["schemas"]["AnonymisedCandidate"][];
            /** Total Count */
            total_count: number;
            /** Capped */
            capped: boolean;
        };
        /** CategorySchema */
        CategorySchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Enabled */
            enabled: boolean;
            /** Skills */
            skills: number[];
            /** Specialties */
            specialties: number[];
            /** Type */
            type: string | null;
            /** Date Added */
            date_added: string | null;
            /** Occupation */
            occupation: string | null;
        };
        /** CompanySchema */
        CompanySchema: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ConnectionRead */
        ConnectionRead: {
            /** Company Id */
            company_id: string;
            /** Name */
            name: string;
            /** Configured */
            configured: boolean;
            /** Connected */
            connected: boolean;
            /** Rest Url Present */
            rest_url_present: boolean;
            /** Detail */
            detail?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobOrderFeedResponse */
        JobOrderFeedResponse: {
            /** Company Id */
            company_id: string;
            /** Jobs */
            jobs: components["schemas"]["JobOrderSchema"][];
            /** Last Checked At */
            last_checked_at: string | null;
        };
        /** JobOrderSchema */
        JobOrderSchema: {
            /** Id */
            id: number;
            address: components["schemas"]["AddressSchema"] | null;
            /** Benefits */
            benefits: string | null;
            /** Bill Rate Category Id */
            bill_rate_category_id: number | null;
            /** Bonus Package */
            bonus_package: string | null;
            /** Branch Code */
            branch_code: string | null;
            /** Certification List */
            certification_list: string | null;
            /** Client Bill Rate */
            client_bill_rate: number | null;
            /** Cost Center */
            cost_center: string | null;
            /** Degree List */
            degree_list: string | null;
            /** Description */
            description: string | null;
            /** Duration Weeks */
            duration_weeks: number | null;
            /** Education Degree */
            education_degree: string | null;
            /** Employment Type */
            employment_type: string | null;
            /** Estimated End Date */
            estimated_end_date: string | null;
            /** External Category Id */
            external_category_id: number | null;
            /** External Id */
            external_id: string | null;
            /** Fee Arrangement */
            fee_arrangement: number | null;
            /** Hours Of Operation */
            hours_of_operation: string | null;
            /** Hours Per Week */
            hours_per_week: number | null;
            /** Is Client Editable */
            is_client_editable: boolean | null;
            /** Is Deleted */
            is_deleted: boolean | null;
            /** Is Interview Required */
            is_interview_required: boolean | null;
            /** Is Jobcast Published */
            is_jobcast_published: boolean | null;
            /** Is Open */
            is_open: boolean | null;
            /** Is Public */
            is_public: number | null;
            /** Is Work From Home */
            is_work_from_home: boolean | null;
            /** Job Board List */
            job_board_list: string | null;
            /** Job Order Rate Card Id */
            job_order_rate_card_id: number | null;
            /** Job Posting Url */
            job_posting_url: string | null;
            /** Mark Up Percentage */
            mark_up_percentage: number | null;
            /** Num Openings */
            num_openings: number | null;
            /** On Site */
            on_site: string | null;
            /** Pay Rate */
            pay_rate: number | null;
            /** Public Description */
            public_description: string | null;
            /** Published Zip */
            published_zip: string | null;
            /** Reason Closed */
            reason_closed: string | null;
            /** Report To */
            report_to: string | null;
            /** Salary */
            salary: number | null;
            /** Salary Unit */
            salary_unit: string | null;
            /** Screener Questions Status */
            screener_questions_status: number | null;
            /** Skill List */
            skill_list: string | null;
            /** Source */
            source: string | null;
            /** Status */
            status: string | null;
            /** Tax Rate */
            tax_rate: number | null;
            /** Tax Status */
            tax_status: string | null;
            /** Title */
            title: string | null;
            /** Travel Requirements */
            travel_requirements: string | null;
            /** Type */
            type: number | null;
            /** Will Relocate */
            will_relocate: boolean | null;
            /** Will Relocate Int */
            will_relocate_int: number | null;
            /** Will Sponsor */
            will_sponsor: boolean | null;
            /** Years Required */
            years_required: number | null;
            /** Date Added */
            date_added: string | null;
            /** Date Closed */
            date_closed: string | null;
            /** Date End */
            date_end: string | null;
            /** Date Last Exported */
            date_last_exported: string | null;
            /** Date Last Modified */
            date_last_modified: string | null;
            /** Date Last Published */
            date_last_published: string | null;
            /** Start Date */
            start_date: string | null;
            /** Time And Labor Enabled Date */
            time_and_labor_enabled_date: string | null;
            /** Branch Id */
            branch_id: number | null;
            /** Client Contact Id */
            client_contact_id: number | null;
            /** Client Corporation Id */
            client_corporation_id: number | null;
            /** Location Id */
            location_id: number | null;
            /** Opportunity Id */
            opportunity_id: number | null;
            /** Report To Client Contact Id */
            report_to_client_contact_id: number | null;
            /** Shift Id */
            shift_id: number | null;
            /** Workers Comp Rate Id */
            workers_comp_rate_id: number | null;
            /** Owner Name */
            owner_name: string | null;
            /** Response User Name */
            response_user_name: string | null;
            /** Published Category */
            published_category: string | null;
            /** Categories */
            categories: string[];
            /** Business Sectors */
            business_sectors: string[];
            /** Skills */
            skills: string[];
            /** Specialties */
            specialties: string[];
        };
        /** JobOrderSyncResponse */
        JobOrderSyncResponse: {
            /** Company Id */
            company_id: string;
            /** Synced Count */
            synced_count: number;
            /** Jobs */
            jobs: components["schemas"]["JobOrderSchema"][];
        };
        /** NewJobOrderCheckResponse */
        NewJobOrderCheckResponse: {
            /** Company Id */
            company_id: string;
            /** New Jobs */
            new_jobs: components["schemas"]["JobOrderSchema"][];
            /** Checked Count */
            checked_count: number;
        };
        /** TaxonomyOption */
        TaxonomyOption: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_companies_companies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySchema"][];
                };
            };
        };
    };
    check_connection_companies__company_id__connection_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_business_sectors_companies__company_id__business_sectors_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessSectorsSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_companies__company_id__categories_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorySchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_companies__company_id__skills_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyOption"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_countries_companies__company_id__countries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyOption"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_latest_jobs_companies__company_id__jobs_get: {
        parameters: {
            query?: {
                count?: number;
            };
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_candidates_search__company_id__candidates_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_new_job_orders_job_orders__company_id__check_new_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewJobOrderCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_new_job_orders_job_orders__company_id__new_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOrderFeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_job_orders_job_orders__company_id__sync_post: {
        parameters: {
            query?: {
                count?: number;
            };
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOrderSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stored_job_orders_job_orders__company_id__stored_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOrderSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
